# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unpack_ipv4=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['count'],
            },
        ),
    ]
