# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pSampler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unpack_ipv4=True)),
                ('count', models.IntegerField(default=1)),
                ('last_request', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['count', 'last_request'],
            },
        ),
        migrations.DeleteModel(
            name='RequestInfo',
        ),
    ]
